### ISSUE TITLE
Instructions on using

### ISSUE THREAD

**Issue by rahul003** [nicc777/macaws-codecommit-pwdel#1]
Could you please provide instructions on how to setup this script?

**Comment by nicc777** [comment]
Hi @rahul003 - I added some installation instruction in the README.md file - hope that helps!

**Comment by nicc777** [comment]
PS: I thought s little more about this and event though I'm not that familiar with Apple script, I'll spend a bit of time trying to find a better way to package and distribute the script.

**Comment by rahul003** [comment]
Thanks for the quick response. That'll get me started. But yeah if you can package it, lot more people would use it!

**Comment by rahul003** [comment]
Awesome it's working, thanks for the script!

**Comment by nicc777** [comment]
Good to hear - I haven't had much change to work on an installation script/file, so check back in a couple of days if you still require one.

**Comment by goldnetonline** [comment]
Hi there

Is there is a way we can change the frequency of time the script runs, 

Thanks

**Comment by nicc777** [comment]
Hi - sorry for the delay - I'll have a look at it later tonight. Just need a break from my day job :-)

**Comment by nicc777** [comment]
@goldnetonline - I have added a dialog at startup to set the delay. I still need to re-package and test the packaging, but you should be able to use the modified script in AppleScript.
